### PR TITLE
[CALCITE-4131] add catch the exception when get the ResultSet value

### PR DESCRIPTION
**Pull request by NobiGo**

### CODE REVIEW

**Comment by NobiGo** [comment]
@julianhyde  Do you have more advice about this PR?

**Comment by julianhyde** [comment]
You need to somehow create a `ResultSet` that will throw. By 'reflective wrappers' I meant create an implementation of `java.lang.reflect.InvocationHandler` so that you can inject your own implementation of `ResultSet`. But first I'd try to write some SQL that blows up at run time. Say divide-by-zero or count from a huge cartesian product.

**Comment by NobiGo** [comment]
@julianhyde  I find another way to test this. Maybe We can dependency Calcite in the test scope. Then we can test this PR by the XMLTRANSFORM function.  What do you think about this?

**Comment by NobiGo** [comment]
@julianhyde Let me know if you agree with mine or not? So I can do some improvement.

**Comment by julianhyde** [comment]
I don't think it would be good to depend on Calcite. That would be cyclic dependency, and it would increase coupling between the projects.

I implemented a test using reflective wrappers in https://github.com/julianhyde/quidem/tree/0023-fetch-error. Take a look.

**Comment by julianhyde** [comment]
Merged as abba7ea227043eaac5f2c230afff576905ee77e1. Thanks for the PR!

**Pull request closed without merging**
